#include <assert.h>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <pthread.h>
#include <queue>
#include <string>
#include <thread>
#include <iostream>
#include <fstream>